/*******************************************************************************
 * This file is protected by Copyright. 
 * Please refer to the COPYRIGHT file distributed with this source distribution.
 *
 * This file is part of REDHAWK IDE.
 *
 * All rights reserved.  This program and the accompanying materials are made available under 
 * the terms of the Eclipse Public License v1.0 which accompanies this distribution, and is available at 
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
// BEGIN GENERATED CODE
package gov.redhawk.ide.codegen.jet.cplusplus.template;

import gov.redhawk.ide.codegen.ImplementationSettings;
import gov.redhawk.ide.codegen.jet.TemplateParameter;
import gov.redhawk.ide.codegen.util.CodegenFileHelper;
import gov.redhawk.model.sca.util.ModelUtil;
import mil.jpeojtrs.sca.scd.SoftwareComponent;
import mil.jpeojtrs.sca.scd.ComponentType;
import mil.jpeojtrs.sca.spd.Implementation;
import mil.jpeojtrs.sca.spd.SoftPkg;
import org.eclipse.core.resources.IResource;
import org.eclipse.core.runtime.CoreException;

/**
 * @generated
 */
public class MakefileAmTemplate
{

  protected static String nl;
  public static synchronized MakefileAmTemplate create(String lineSeparator)
  {
    nl = lineSeparator;
    MakefileAmTemplate result = new MakefileAmTemplate();
    nl = null;
    return result;
  }

  public final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = "ossieName = ";
  protected final String TEXT_2 = NL + "bindir = $(prefix)/";
  protected final String TEXT_3 = "/";
  protected final String TEXT_4 = "/";
  protected final String TEXT_5 = "/";
  protected final String TEXT_6 = "/" + NL + "bin_PROGRAMS = ";
  protected final String TEXT_7 = NL + NL + "xmldir = $(prefix)/";
  protected final String TEXT_8 = "/";
  protected final String TEXT_9 = "/";
  protected final String TEXT_10 = "/" + NL + "dist_xml_DATA = ";
  protected final String TEXT_11 = " ";
  protected final String TEXT_12 = " ";
  protected final String TEXT_13 = NL + NL + "distclean-local:" + NL + "\trm -f config.*" + NL + "\trm -rf autom4te.cache" + NL + "\trm -f acinclude.m4" + NL + "\trm -f aclocal.m4" + NL + "\trm -f configure" + NL + "\trm -f depcomp" + NL + "\trm -f install-sh" + NL + "\trm -f ltmain.sh" + NL + "\trm -f Makefile.in" + NL + "\trm -f missing" + NL + "\trm -rf .deps" + NL + "" + NL + "# Sources, libraries and library directories are auto-included from a file" + NL + "# generated by the REDHAWK IDE. You can remove/modify the following lines if" + NL + "# you wish to manually control these options." + NL + "include $(srcdir)/Makefile.am.ide";
  protected final String TEXT_14 = NL;
  protected final String TEXT_15 = "_SOURCES = $(redhawk_SOURCES_auto)";
  protected final String TEXT_16 = NL;
  protected final String TEXT_17 = "_CXXFLAGS = -Wall $(PROJECTDEPS_CFLAGS) $(BOOST_CPPFLAGS) $(INTERFACEDEPS_CFLAGS) $(redhawk_INCLUDES_auto)";
  protected final String TEXT_18 = NL;
  protected final String TEXT_19 = "_LDADD = $(PROJECTDEPS_LIBS) $(BOOST_LDFLAGS) $(BOOST_THREAD_LIB) $(INTERFACEDEPS_LIBS) $(redhawk_LDADD_auto)";
  protected final String TEXT_20 = NL;
  protected final String TEXT_21 = "_LDFLAGS = -Wall $(redhawk_LDFLAGS_auto)";
  protected final String TEXT_22 = NL;

  public String generate(Object argument) throws CoreException
  {
    final StringBuffer stringBuffer = new StringBuffer();
     
    TemplateParameter template = (TemplateParameter) argument;
    ImplementationSettings implSettings = template.getImplSettings();
    IResource resource = ModelUtil.getResource(implSettings);
    Implementation impl = template.getImpl();
    SoftPkg softPkg = (SoftPkg) impl.eContainer();
    
    String sdrSubDir = "dom";
    String subFolder = "components";

    SoftwareComponent component = softPkg.getDescriptor().getComponent();
    final ComponentType scdComponentType = SoftwareComponent.Util.getWellKnownComponentType(component); 
    if (scdComponentType == ComponentType.DEVICE) {
    	sdrSubDir = "dev";
     	subFolder = "devices";
    } else if (scdComponentType == ComponentType.SERVICE) {
    	sdrSubDir = "dev";
     	subFolder = "services";
    }
    
    String xmlLocation = "";
    for (String temp : implSettings.getOutputDir().split("/")) {
      if (temp.length() > 1) {
        xmlLocation += "../";
      }
    }

    final String fileprefix = CodegenFileHelper.getPreferredFilePrefix(softPkg, implSettings);

    stringBuffer.append(TEXT_1);
    stringBuffer.append(fileprefix);
    stringBuffer.append(TEXT_2);
    stringBuffer.append(sdrSubDir);
    stringBuffer.append(TEXT_3);
    stringBuffer.append(subFolder);
    stringBuffer.append(TEXT_4);
    stringBuffer.append(resource.getProject().getName());
    stringBuffer.append(TEXT_5);
    stringBuffer.append(implSettings.getOutputDir());
    stringBuffer.append(TEXT_6);
    stringBuffer.append(fileprefix);
    stringBuffer.append(TEXT_7);
    stringBuffer.append(sdrSubDir);
    stringBuffer.append(TEXT_8);
    stringBuffer.append(subFolder);
    stringBuffer.append(TEXT_9);
    stringBuffer.append(resource.getProject().getName());
    stringBuffer.append(TEXT_10);
    stringBuffer.append(xmlLocation);
    stringBuffer.append(ModelUtil.getPrfFileName(softPkg.getPropertyFile()));
    stringBuffer.append(TEXT_11);
    stringBuffer.append(xmlLocation);
    stringBuffer.append(ModelUtil.getScdFileName(softPkg));
    stringBuffer.append(TEXT_12);
    stringBuffer.append(xmlLocation);
    stringBuffer.append(ModelUtil.getSpdFileName(softPkg));
    stringBuffer.append(TEXT_13);
    stringBuffer.append(TEXT_14);
    stringBuffer.append(fileprefix);
    stringBuffer.append(TEXT_15);
    stringBuffer.append(TEXT_16);
    stringBuffer.append(fileprefix);
    stringBuffer.append(TEXT_17);
    stringBuffer.append(TEXT_18);
    stringBuffer.append(fileprefix);
    stringBuffer.append(TEXT_19);
    stringBuffer.append(TEXT_20);
    stringBuffer.append(fileprefix);
    stringBuffer.append(TEXT_21);
    stringBuffer.append(TEXT_22);
    return stringBuffer.toString();
  }
}

// END GENERATED CODE