#ifndef _FILE_ONE_IDL_
/**
 * This file is protected by Copyright.
 * Please refer to the COPYRIGHT file distributed with this source distribution.
 *
 * This file is part of REDHAWK IDE.
 *
 * All rights reserved.  This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License v1.0 which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html.
 *
 */
#define _FILE_ONE_IDL_

//#include <ossie/CF/cf.idl>
#include <ossie/CF/cf.idl>

module EXAMPLE {
    typedef short MyType;
    const short MY_CONST_ZERO = 0;
    const short MY_CONST_ONE = 1;

    typedef sequence<string> StringArray;

    struct AStructure {
        short field1;
        long field2;
        double field3;
    };

    exception MajorError {
        MyType error_code;
        string message;
    };

    interface SomeInterface {
        void someFunc(in CF::DataType a, out string b);
    };
};
#endif
